import { Sprout, Package, Pill, ClipboardList } from "lucide-react";
import { zaminApi } from "../../api/zaminApi";
import { mahsulotApi } from "../../api/mahsulotApi";
import { aptekaApi } from "../../api/aptekaApi";
import { jobsApi } from "../../api/jobsApi";
import {
  CITIES,
  PRODUCT_CATEGORIES,
  MEDICINE_CATEGORIES,
  cityLabel,
  productCategoryLabel,
  medicineCategoryLabel,
  normalizeCity,
  normalizeProductCategory,
  normalizeMedicineCategory,
} from "../../lib/catalog";
import { PLACEHOLDER_IMG } from "../../lib/images";

const num = (v) => Number(v) || 0;
const text = (v) => String(v ?? "").trim();

const ownerExtra = (t, user) => ({
  farmerName: user.userName || user.name || t("defaultFarmerName"),
  farmerPhone: user.userPhone || user.phone || "",
});

export const SECTIONS = [
  {
    key: "zamin",
    api: zaminApi,
    icon: Sprout,
    color: "text-emerald-600",
    statKey: "landRent",
    panelKey: "manageLandsTitle",
    addKey: "addLand",
    editKey: "editLand",
    emptyKey: "noLands",
    deleteConfirmKey: "deleteLandConfirm",
    addedKey: "landAddedToMarket",
    updatedKey: "landUpdated",
    deletedKey: "landDeleted",
    title: (item) => item.name,
    meta: (t, item) => [
      cityLabel(t, item.city),
      `${item.price} ${t("somoniShort")}`,
      `${t("landSize")}: ${item.leftovers ?? 0}`,
    ],
    fields: [
      { name: "name", labelKey: "landObjectNameLabel", type: "text", required: true },
      { name: "img", labelKey: "landImgLabel", type: "image" },
      { name: "city", labelKey: "cityOnlyLabel", type: "select", options: CITIES, half: true },
      { name: "leftovers", labelKey: "landAreaLabel", type: "number", half: true },
      { name: "price", labelKey: "landRentPriceLabel", type: "number", required: true },
      { name: "desc", labelKey: "landDescLabel", type: "text" },
    ],
    toForm: (item) => ({
      name: item?.name || "",
      img: item?.img || "",
      city: normalizeCity(item?.city),
      leftovers: item?.leftovers ?? "",
      price: item?.price ?? "",
      desc: item?.desc || "",
    }),
    toPayload: (form, t) => ({
      type: "zamin",
      name: text(form.name) || t("landDefaultName"),
      img: text(form.img) || PLACEHOLDER_IMG,
      city: form.city,
      leftovers: num(form.leftovers),
      price: num(form.price),
      desc: text(form.desc) || t("landNoExtraInfo"),
    }),
    createExtra: ownerExtra,
  },
  {
    key: "mahsulot",
    api: mahsulotApi,
    icon: Package,
    color: "text-amber-600",
    statKey: "market",
    panelKey: "manageProductsTitle",
    addKey: "addProduct",
    editKey: "editProduct",
    emptyKey: "noProducts",
    deleteConfirmKey: "deleteProductConfirm",
    addedKey: "productAdded",
    updatedKey: "productUpdated",
    deletedKey: "productDeleted",
    title: (item) => item.name,
    meta: (t, item) => [
      productCategoryLabel(t, item.category),
      cityLabel(t, item.city),
      `${item.price} ${t("somoniShort")}`,
      `${item.leftovers ?? 0} ${t("pieceShort")}`,
    ],
    fields: [
      { name: "name", labelKey: "productNameLabel", type: "text", required: true },
      { name: "img", labelKey: "productImgLabel", type: "image" },
      { name: "category", labelKey: "categoryLabel", type: "select", options: PRODUCT_CATEGORIES, half: true },
      { name: "city", labelKey: "cityOnlyLabel", type: "select", options: CITIES, half: true },
      { name: "price", labelKey: "priceSomoniLabel", type: "number", required: true, half: true },
      { name: "leftovers", labelKey: "quantity", type: "number", required: true, half: true },
      { name: "description", labelKey: "desc", type: "text" },
    ],
    toForm: (item) => ({
      name: item?.name || "",
      img: item?.img || "",
      category: normalizeProductCategory(item?.category),
      city: normalizeCity(item?.city),
      price: item?.price ?? "",
      leftovers: item?.leftovers ?? "",
      description: item?.description || "",
    }),
    toPayload: (form) => ({
      name: text(form.name),
      img: text(form.img) || PLACEHOLDER_IMG,
      category: form.category,
      city: form.city,
      price: num(form.price),
      leftovers: num(form.leftovers),
      description: text(form.description),
    }),
    createExtra: ownerExtra,
  },
  {
    key: "apteka",
    api: aptekaApi,
    icon: Pill,
    color: "text-rose-600",
    statKey: "pharmacyTitle",
    panelKey: "managePharmacyTitle",
    addKey: "addMedicine",
    editKey: "editMedicine",
    emptyKey: "noMedicines",
    deleteConfirmKey: "deleteMedicineFromMarketConfirm",
    addedKey: "medicineAdded",
    updatedKey: "medicineUpdated",
    deletedKey: "medicineDeleted",
    title: (item) => item.name,
    meta: (t, item) => [
      medicineCategoryLabel(t, item.category),
      cityLabel(t, item.city),
      `${item.price} ${t("somoniShort")}`,
    ],
    fields: [
      { name: "name", labelKey: "medicineNameLabel", type: "text", required: true },
      { name: "img", labelKey: "medicineImgLabel", type: "image" },
      { name: "category", labelKey: "categoryLabel", type: "select", options: MEDICINE_CATEGORIES, half: true },
      { name: "city", labelKey: "cityOnlyLabel", type: "select", options: CITIES, half: true },
      { name: "price", labelKey: "priceSomoniLabel", type: "number", required: true, half: true },
      { name: "leftovers", labelKey: "quantity", type: "number", required: true, half: true },
      { name: "description", labelKey: "desc", type: "text" },
    ],
    toForm: (item) => ({
      name: item?.name || "",
      img: item?.img || "",
      category: normalizeMedicineCategory(item?.category),
      city: normalizeCity(item?.city),
      price: item?.price ?? "",
      leftovers: item?.leftovers ?? "",
      description: item?.description || "",
    }),
    toPayload: (form) => ({
      name: text(form.name),
      img: text(form.img),
      category: form.category,
      city: form.city,
      price: num(form.price),
      leftovers: num(form.leftovers),
      description: text(form.description),
    }),
    createExtra: ownerExtra,
  },
  {
    key: "jobs",
    api: jobsApi,
    icon: ClipboardList,
    color: "text-sky-600",
    statKey: "requestsTitle",
    panelKey: "manageRequestsTitle",
    addKey: "createRequestTitle",
    editKey: "editRequestTitle",
    emptyKey: "noRequestsYet",
    deleteConfirmKey: "deleteRequestConfirm",
    addedKey: "requestAdded",
    updatedKey: "requestUpdated",
    deletedKey: "requestDeleted",
    title: (item) => item.companyName,
    meta: (t, item) => [
      item.productName,
      `${item.volume} — ${t("requiredVolumeLabel")}`,
      item.creatorName,
    ],
    fields: [
      { name: "companyName", labelKey: "companyPlaceholder", type: "text", required: true },
      { name: "productName", labelKey: "productPlaceholder", type: "text", required: true },
      { name: "volume", labelKey: "volumePlaceholder", type: "text", required: true },
      { name: "description", labelKey: "desc", type: "text" },
    ],
    toForm: (item) => ({
      companyName: item?.companyName || "",
      productName: item?.productName || "",
      volume: item?.volume ?? "",
      description: item?.description || "",
    }),
    toPayload: (form) => ({
      companyName: text(form.companyName),
      productName: text(form.productName),
      volume: text(form.volume),
      description: text(form.description),
    }),
    createExtra: (t, user) => ({
      creatorName: user.userName || user.name || t("defaultFarmerName"),
      creatorPhone: user.userPhone || user.phone || "",
      createdAt: new Date().toISOString(),
    }),
  },
];

export const SECTION_BY_KEY = Object.fromEntries(SECTIONS.map((s) => [s.key, s]));
